### ISSUE TITLE
Letter 'T' in position 1 

### ISSUE THREAD

**Issue by jamesbowman** [joeycastillo/Sensor-Watch#10]
Drawing the letters "ST" in positions 0,1 like this:

        char buf[11];
        sprintf(buf, "ST  %2d%02d%02d", 0, 0, 0);
        watch_display_string(buf, 0);

gives the T without the vertical segments:

![image](https://user-images.githubusercontent.com/894763/131229195-2d747bf1-69e7-494d-855e-4c4ea2d328ea.png)

Perhaps some special cases could be made for ``Character_Set[]`` for positions 0 and 1?

**Comment by joeycastillo** [comment]
I think this is a good case for a special case; down to add it. 

I also last week made [a table](https://github.com/joeycastillo/Sensor-Watch/wiki/Character-Map) with all the characters in the character set, and which positions they work in. B and D also may be candidates for a special case; the extra segment to the left of positions 0 and 1 *might* make them slightly more recognizable.
