### ISSUE TITLE
CC2640

### ISSUE THREAD

**Issue by MstrVLT** [joeycastillo/Sensor-Watch#11]
Can we expect a project with CC2540 / CC2640 in the future? (The BeetleBle uses a CC2540 with ATmega328, but it's a huge size 6 x 6 mm)
CC2640 size is 4 × 4 mm RSM VQFN32 (10 GPIOs)
Add a vibration motor from junk mobile phone and you have a great smartwatch (actually still need e-inc screen)

**Comment by joeycastillo** [comment]
I do not have any plans in this direction, but if the required components are small enough, they may fit on a sensor board; alternatively, it may be possible to incorporate this component into another design based off of this one. The designs are open source; I'd encourage you to build on it! But I don't think this needs to be tracked an issue. 

Thanks for the suggestion!
