### ISSUE TITLE
Initiation guide

### ISSUE THREAD

**Issue by elalemanyo** [joeycastillo/Sensor-Watch#12]
Hi,
I love the project, but I have to admit that I don't really know how to start. It would be a great help if there was a small guide on how to get started 🙈

Thank you very much.

**Comment by joeycastillo** [comment]
I have added [the quick start guide](https://joeycastillo.github.io/Sensor-Watch-Documentation/Sensor%20Watch%20Quick%20Start.pdf) to the documentation site. I will likely revise this document based on feedback from the first folks who made use of it, but it's a start.
