### ISSUE TITLE
Anyway to get console output from a watch face running in the emulator?

### ISSUE THREAD

**Issue by jdsiddon** [joeycastillo/Sensor-Watch#121]
Anyway to get console output on to the emulator page? The filesystem.c file uses `printf` to get output but can't seem to figure out a way to get console output from my custom watch face.

**Comment by wryun** [comment]
printf from your watch face should work (does for me, at least). Make sure to include a '\n'.

**Comment by jdsiddon** [comment]
Worked perfect! Thank you @wryun !!!
