### ISSUE TITLE
[FEATURE REQUEST] Add description to repo

### ISSUE THREAD

**Issue by darigovresearch** [joeycastillo/Sensor-Watch#139]
Would be helpful to add a description to the repository to help differentiate it from other repositories in your repository list.

Would suggest the following if you think it's a good idea

```
A board replacement for the classic Casio F-91W wristwatch
```

![image](https://user-images.githubusercontent.com/30328618/202868622-5a6603fb-181d-482e-93c3-76dadee50f7d.png)

**Comment by joeycastillo** [comment]
Thanks for pointing this out, and for the suggestion! I've added it. 😄

**Comment by darigovresearch** [comment]
@joeycastillo You're very welcome, thanks for adding it!
