### ISSUE TITLE
Index out of bounds error (SIGSEGV) in emulator when setting longitude on sunrise/sunset face

### ISSUE THREAD

**Issue by eshrh** [joeycastillo/Sensor-Watch#198]
Steps to reproduce on my computer:

0. Clone
1. cd movement/make
2. emmake make
3. On the emulator:
	1. m m (switch to sunrise/sunset face)
	2. long press a (enter edit mode)
	3. l l l l l (advance to LO)
	4. l (advance to first digit)
	5. a (set hundreds to 1)
	6. l l l l l (advance to sunrise/sunset)

On firefox, the last l causes the light to stay on and throws an index out of bounds error somewhere in the wasm.
On chromium, the webpage crashes and shows SIGSEGV.

Any thoughts?

It doesn't seem to crash on every latitude entered, just some values every time.

I also have this error, not sure if it's relevant:
```
../../littlefs/lfs.c:1229:error: Corrupted dir pair at {0x0, 0x1}
Ignore that error! Formatting filesystem...
Filesystem mounted with 7680 bytes free.
```

**Comment by WesleyAC** [comment]
I can reproduce this in the simulator (although notably it doesn't seem to affect the hardware, possibly the overflow is happening but not overwriting anything important)
