### ISSUE TITLE
Missing `TOTP-MCU` dir at `./movement/lib` (?)

### ISSUE THREAD

**Issue by rcassani** [joeycastillo/Sensor-Watch#243]
Hi, 

When building the watch FW and got this error:

```
$ make

git submodule update --init
make: *** No rule to make target '../lib/TOTP-MCU/sha1.c', needed by 'build/sha1.o'.  Stop.
make: *** Waiting for unfinished jobs....
```
As the issue seemed to be a typo, I just created a symbolic link, `TOTP-MCU`, to `TOTP`, a build without trouble

**Comment by wryun** [comment]
I suspect you just needed a `make clean` to fix this one. Perhaps you could try doing that and removing the symlink and seeing if it works?

**Comment by rcassani** [comment]
Thanks @wryun, that fixed it
