### ISSUE TITLE
timer face only shows 5 of 9 presets

### ISSUE THREAD

**Issue by 814d3** [joeycastillo/Sensor-Watch#245]
Hi all and hi @TheOnePerson,

I'm using my Sensor Watch since Jan/Feb '23 without any changes in the firmware and without battery replacements and I recognized today, that I can only scroll from preset 1 to 5. After 5 it jumps to 1 again. I remember that I scrolled through all 9 presets one or two weeks ago. 
I tried to do some adjustments of the given presets, hoping this could bring back all 9 presets, but it didn't. Is there anything I can do/try?
Thanks and greetings

**Comment by TheOnePerson** [comment]
Hi @814d3, I guess this is just a handling issue: When you „scroll“ through the timers in normal mode by short pressing the alarm button, only those timers with a valid pre-set time will show up. Empty timers are not shown there. This is to avoid forcing the user pushing all the way through all nine timers when he/she, perhaps by accident, has pressed the alarm button once. When you are in settings mode (light button long press) and the timer number is blinking, you can cycle through all of the timers, whether set or unset. 
Does this solve your problem?

**Comment by TheOnePerson** [comment]
Yes, please do so! I cannot rule out the possibility of some strange edge cases causing a messing up of the stored timers. But for now, I will close this issue.
