### ISSUE TITLE
Timer face loop broken.

### ISSUE THREAD

**Issue by ysftaha** [joeycastillo/Sensor-Watch#246]
# Summary
The timer face breaks after the second loop.
# Steps to reproduce
1. set a timer for 15 minutes
2. set to loop
# Result
After the second loop, the face turns into nonsense
![IMG_3459](https://github.com/joeycastillo/Sensor-Watch/assets/42289530/b821a9e3-8312-41d1-8071-3b84b296b9c8)
Image by @TheOnePerson

**Comment by TheOnePerson** [comment]
I created PR #247 and tested it on my wrist. Looks good then.
