### ISSUE TITLE
LED always on

### ISSUE THREAD

**Issue by roguepullrequest** [joeycastillo/Sensor-Watch#284]
LITE pcb the LED just stays full YELLOW. Pressing the Light button does turn off the GREEN for the set duration. 

Am i missing some default value or something.

**Comment by roguepullrequest** [comment]
I did use the color RED. Sadly the Green led has burnt out because it was on too long.

**Comment by aronhegedus** [comment]
I hit this today, and `make COLOR=RED` worked for me. I have a red board.

**Comment by roguepullrequest** [comment]
So i have use clean repo and still the same issue. I always make sure color is RED.
i even tried other machines to rebuild and still same issue. 


The LED both green/red stay on.

**Comment by joeycastillo** [comment]
To be clear, you're running `make COLOR=RED` (with both COLOR and RED in all capital letters)?

**Comment by roguepullrequest** [comment]
> To be clear, you're running `make COLOR=RED` (with both COLOR and RED in all capital letters)?

Yup. Had to triple check my shell history to be sure but using `make COLOR=RED` to build.

Thanks for everything.

**Comment by h6y3** [comment]
> > To be clear, you're running `make COLOR=RED` (with both COLOR and RED in all capital letters)?
> 
> Yup. Had to triple check my shell history to be sure but using `make COLOR=RED` to build.
> 
> Thanks for everything. 

I ran into this issue as well. I did a make clean before I issued the make command and that did the trick for me.

**Comment by theorangerider** [comment]
Seems like this issue can be closed?

**Comment by WesleyAC** [comment]
Going to close this as it seems to be the `COLOR` issue? @roguepullrequest if you're still having problems, definitely open a new issue.
