### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [joeycastillo/Sensor-Watch#3]
Hello!

I found link to this project from https://hackaday.com/2021/08/08/wristwatch-pcb-swaps-must-be-in-the-air/

Could you please add information about license of this repository — is it allowed to copy, change and use the code, images and PCB files in any purpose?
It would be great to see any popular open source license.

**Comment by joeycastillo** [comment]
I have added license information here: https://github.com/joeycastillo/Sensor-Watch/blob/main/LICENSE.md

The hardware designs are CC-BY-SA 4.0; the software support library is a bit complicated at the moment, but the goal is for it all to be MIT.
