### ISSUE TITLE
totp_face

### ISSUE THREAD

**Issue by Haifisch92** [joeycastillo/Sensor-Watch#343]
hi i ve tried to deploy totp_face but output code on watch are different from app authenticator , so i have tried to change algorithm with sha256 without good result . in the end i have tried to flash firmware with the default TOTP secret and add TOTP secret on my authenticator app but code still not match ...

someone flashed this face with good result???

**Comment by Haifisch92** [comment]
from emulator on https://sensor-watch-builder.fly.dev/ , output code match with google auth, i dont understand what i'm doing wrong

**Comment by WesleyAC** [comment]
Have you set the time correctly on the watch, including the timezone offset? My guess would be that you didn't set the timezone.

**Comment by Haifisch92** [comment]
yeah thanks a lot , the problem was timezone
