### ISSUE TITLE
Tomato watch face not working anymore

### ISSUE THREAD

**Issue by h6y3** [joeycastillo/Sensor-Watch#353]
I am not sure what happened, but it appears that the tomato watch face has stopped working correctly. When I start a pomodoro (either work or rest) the timer never ends, and it eventually starts displaying strange numbers as if it was rolling on itself. 

I pulled the battery hoping it would "fix" itself but it didn't so my next step is to just load up new firmware and hope it is fixed. 

Anybody have any ideas what could have caused this or if there was an update that would address this?

**Comment by h6y3** [comment]
Here's a picture of the watch face which is in break mode and it's just doing all sorts of crazy things. :)

![image](https://github.com/joeycastillo/Sensor-Watch/assets/1714217/5c1d434d-723a-4def-afe5-f4199901bbb6)

**Comment by tahnok** [comment]
I think this is the timestamp/ leapyear bug again (see other recent issues)
that should be fixed by upgrading the firmware

**Comment by joeycastillo** [comment]
It looks like it was related to the leap year. If you were using a custom firmware, please rebuild and reflash with the latest code on main; if you were using one of the prebuilt alternative firmware images, you should be able to [download an updated version of it here](https://www.sensorwatch.net/docs/firmware/prebuilt/).

**Comment by h6y3** [comment]
Thank you! This makes sense and the timing corresponds with the breakage. 

I appreciate all of the support - it's an amazing platform!
