### ISSUE TITLE
Watch Freezes at Midnight in LE

### ISSUE THREAD

**Issue by Dabaraboo** [joeycastillo/Sensor-Watch#359]
![photo_2024-01-16_19-57-55](https://github.com/joeycastillo/Sensor-Watch/assets/14141087/e7ca0d42-40c7-4298-b433-d2b2104c6291)
I've woken up to find the sensor watch frozen at midnight a couple times, its unresponsive to an alarm press to wake, and the second ticker is still running. I'm wondering if anyone else has experienced this issue?  
I've been using the unofficial firmware builder.

**Comment by 814d3** [comment]
How did you solve the issue? Was it because of an outdated firmware version?

**Comment by Dabaraboo** [comment]
> How did you solve the issue? Was it because of an outdated firmware version?

**Comment by Dabaraboo** [comment]
It may be solved with the updated firmware. closed the issue given the lack of relevant info I had. 
Accidentally closed it again just now because I have no idea what i'm doing, lol
