### ISSUE TITLE
Flashing firmware instructions for the command line

### ISSUE THREAD

**Issue by orhun** [joeycastillo/Sensor-Watch#409]
Hello!

Is there any guide for flashing firmware from the terminal? I checked [the documentation](https://www.sensorwatch.net/docs/firmware/flashing/) but unfortunately it is not suitable for my case.

Thank you!

**Comment by matheusmoreira** [comment]
Hello! Are you running Linux?

Linux should automatically detect and expose the watch to the system as a mass storage device. Then you can mount it and copy the firmware to the root directory of the device. That will flash the firmware.

I wrote a simple script to do it automatically. It's on my laptop and I'm at work right now. I'll share it here when I get back home.

**Comment by orhun** [comment]
Hey, that worked thanks! I simply `mount`ed it and copied the firmware :)
