### ISSUE TITLE
WATCHBOOT inoperative on Ubuntu 22.04 and MacOS

### ISSUE THREAD

**Issue by tareed** [joeycastillo/Sensor-Watch#455]
Unable to mount the watch (WATCHBOOT).
System log shows the Tiny USB device but assigns it as a ACM device. 
With the ACM detection disabled, still shows device detected, but "not an MTP device".
uDev rule or process to allow the watch to be programmed?
Similar results with latest MacOS.

**Comment by tahnok** [comment]
It sounds like the watch is not in bootloader mode. You need to double tap
reset while it's plugged in and you should see the LED blink

**Comment by jpdbryant** [comment]
One thing that got me - you have to double-tap _quite fast_
