### ISSUE TITLE
Doxygen broken on GitHub Pages

### ISSUE THREAD

**Issue by a2** [joeycastillo/Sensor-Watch#48]
I think the fabc6d28eaf6e0227c68673d3c564c31f4c01a17 commit broke the Doxygen setup on [GitHub Pages](https://joeycastillo.github.io/Sensor-Watch). I don't have Doxygen on my local machine but I wanted to flag this up since the simulator PR moved some files around.

**Comment by joeycastillo** [comment]
Thanks for flagging this! It just involved pointing it to the new location in `watch-library/shared`, should be good now.
