### ISSUE TITLE
Easier UF2 mode?

### ISSUE THREAD

**Issue by tahnok** [joeycastillo/Sensor-Watch#81]
While working on #76 I find myself flashing firmware repeatedly and getting annoyed at finding the reset button to double tap each time. Is there a way to reboot into UF2 mode with code in normal mode? That way you could extend the movement USB cli to have a `reboot` command, or do some other trick so that the programming computer could reset the sensorwatch into UF2 mode

**Comment by joeycastillo** [comment]
This is a great idea! And sorry for the delay in responding; this issue caught me during a week I was traveling. I'm adding a new function, `watch_reset_to_bootloader()`, that does exactly this. 

Background: to realize the double tap reset function, the UF2 bootloader sets a magic number at a specific location in RAM when the board resets. It then waits 500 ms and clears it. If the user taps reset a second time within that 500 ms interval, the magic number is still set; the bootloader recognizes that case, and takes control.

The `watch_reset_to_bootloader` function fakes out the bootloader by setting the magic number, and immediately calling `NVIC_SystemReset()`. At that point, the bootloader believes that this is the second tap of the reset button, and enters bootloader mode. Try it out and reopen if you find any issues, but I think it should be good to go as soon as I close this!
